name: sample-project-training-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - pip:
      - azure-ai-ml>=1.12.0
      - joblib>=1.3.2
      - numpy>=1.24.4
      - pandas>=2.1.4
      - scikit-learn>=1.3.2
